# Generated by Django 4.2.6 on 2023-11-08 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_full_name_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
