# Generated by Django 4.2.5 on 2023-10-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
    ]
