# Generated by Django 4.2.6 on 2023-11-17 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xfilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default=1)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('All', '전체'), ('Daily', '일상'), ('Sports', '스포츠'), ('Politics', '정치'), ('Technology', '기술'), ('Entertainment', '엔터테인먼트'), ('Science and Nature', '과학과 자연'), ('Gaming', '게임'), ('Books and Literature', '책과 문학'), ('Health and Fitness', '건강과 피트니스'), ('Travel', '여행'), ('Food and Cooking', '음식과 요리'), ('Art and Creativity', '미술과 창작'), ('Technology Help/Support', '기술 지원/도움말')], default='All', max_length=200)),
                ('voter', models.ManyToManyField(related_name='voter_xfilter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default=1)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('voter', models.ManyToManyField(related_name='voter_comment', to=settings.AUTH_USER_MODEL)),
                ('xfilter_id', models.ForeignKey(db_column='xfilter_id', on_delete=django.db.models.deletion.CASCADE, to='board.xfilter')),
            ],
        ),
    ]
