# Generated by Django 4.2.6 on 2023-11-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='report_author',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='content',
            new_name='report_content',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
    ]
