# Generated by Django 4.2.6 on 2023-11-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_report_report_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_content',
            new_name='content',
        ),
    ]
