# Generated by Django 4.2.6 on 2023-11-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_comment_create_date_alter_comment_modify_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xfilter',
            name='subject',
        ),
    ]
