# Generated by Django 4.2.6 on 2023-11-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_rename_report_author_report_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(default='ETC', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
