# Generated by Django 4.2.6 on 2023-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_report_category_report_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, default='ETC', max_length=200),
        ),
    ]
