# Generated by Django 4.2.6 on 2023-11-08 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0009_remove_xfilter_author_remove_xfilter_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfilter',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
