# Generated by Django 4.2.6 on 2023-11-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_xfilter_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xfilter',
            name='author',
            field=models.TextField(default=1),
        ),
    ]
