# Generated by Django 4.2.6 on 2023-11-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_remove_comment_modify_date_remove_comment_voter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.TextField(default=1),
        ),
    ]
