# Generated by Django 4.2.6 on 2023-11-13 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0016_alter_comment_xfilter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voter',
            field=models.ManyToManyField(related_name='voter_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xfilter',
            name='voter',
            field=models.ManyToManyField(related_name='voter_xfilter', to=settings.AUTH_USER_MODEL),
        ),
    ]
