# Generated by Django 4.2.6 on 2023-11-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_comment_voter_xfilter_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfilter',
            name='category',
            field=models.CharField(choices=[('All', '전체'), ('Daily', '일상'), ('Sports', '스포츠'), ('Politics', '정치')], default='All', max_length=20),
        ),
    ]
