# Generated by Django 4.2.6 on 2023-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_xfilter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfilter',
            name='member_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
