# Generated by Django 4.2.6 on 2023-11-14 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0019_xfilter_member_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xfilter',
            name='member_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
